[package]
name = "keylime_node"
version = "0.1.0"
authors = ["Pei Jia <ljia@redhat.com>", "Mark Bestavros <mbestavr@redhat.com>"]

[dependencies]
base64 = "0.9.3"
flate2 = "1.0.4"
futures = "0.1.24"
hex = "0.3.2"
hyper = "0.12"
libc = "0.2.43"
log = "0.4"
no-panic = "0.1.6"
openssl = "0.10.15"
pretty_env_logger = "0.2.0"
rustc-serialize = "0.3.24"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0"
tempfile = "3.0.4"
tokio-io = "0.1"
